# ---------------------------------------------
# Copyright 2015 for Zen. All Rights Reserved.
# ---------------------------------------------

# docker / kubernetes image


FROM python:3.14 as environment
WORKDIR /application
ENV TZ=Asia/Shanghai

ADD docker/.bashrc /root/.bashrc
ADD docker/debian.sources /etc/apt/sources.list.d/debian.sources
RUN apt-get update -y && apt-get install -y vim

RUN pip install --no-cache-dir --index-url https://mirrors.aliyun.com/pypi/simple --upgrade pdm
RUN pdm update --no-self --update-all --unconstrained --verbose
RUN pdm install --no-self --no-editable --no-cache --verbose

FROM quant:environment as test
ADD . /application
CMD bash run.sh test
