# stable version image


FROM python:3.12 as environment
ENV TZ=Asia/Shanghai
WORKDIR /

ADD docker/.bashrc /root/.bashrc
ADD docker/debian.sources /etc/apt/sources.list.d/debian.sources
RUN apt-get update -y && apt-get install -y vim

ADD requirements.txt /requirements.txt
RUN pip install --index-url https://mirrors.aliyun.com/pypi/simple --upgrade pip setuptools
RUN pip install --index-url https://mirrors.aliyun.com/pypi/simple --requirement requirements.txt



FROM quant:environment-latest as stable
WORKDIR /application
ADD . /application
CMD ["bash", "run.sh"]



FROM quant:environment-latest as compile
WORKDIR /application
ADD . /application
RUN python project/setup.py build && python project/setup.py clean
CMD ["bash", "run.sh"]
