site_name: ChatGPT 算法模型
copyright: Copyright &copy; 2023

docs_dir: ../documents
site_dir: ../homepage
use_directory_urls: false

repo_name: chatgpt-modeling
repo_url: https://gitlab.fosun.com/fosun-allience/di/algorithms/chatgpt-modeling.git

nav:
    - 主页: index.md
    - 自然语言转化 SQL: markdowns/nl-sql.md
    - 内容生成: markdowns/generate-content.md
    - 更新日志: changelog.md

theme:
    favicon: extra/favicon.ico
    features:
        - content.code.copy
        - navigation.top
        - search.highlight
        - search.suggest
    font: false
    icon:
        admonition:
            info: material/book
            quote: material/comment-quote
        repo: material/gitlab
    language: zh
    logo: extra/logo.svg
    name: material

plugins:
    - autolinks:
    - search:
    - table-reader:

exclude_docs: |
    run.py
    mkdocs.yml
    routes/
    *.xlsx
    *.json

extra_css:
    - extra/blocks.css
    - extra/extra.css

validation:
    absolute_links: ignore

markdown_extensions:
    - abbr:
    - admonition:
    - attr_list:
    - pymdownx.details:
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
        linenums_style: pymdownx-table
    - pymdownx.inlinehilite:
    - pymdownx.keys:
    - pymdownx.mark:
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.superfences:
        preserve_tabs: true
    - pymdownx.tabbed:
        alternate_style: true
    - tables:
